### ISSUE TITLE
Each method should do only one thing

### ISSUE THREAD

**Issue by AlexKap23** [Sosa09/TicTacToe#1]
https://github.com/Sosa09/TicTacToe/blob/5ece4deb3de4ac4d64fa7dc82f368814964aebcc/TicTacToe/Program.cs#L93

This method has been created to determine which player's turn it is. But  it also handles player's next moves. By reading the name for sure you can't understand that both actions will happen. 

In my opinion this method should be split into 2 methods. One for actually determining the player's turn and one for the gameplay.

**Comment by Sosa09** [comment]
Code refactored
Intrudocued new variables for currentPlayer
see picture
![image](https://github.com/user-attachments/assets/3bc3191f-f1a4-4af0-8e5e-ae4a535060de)

passing those variables in determinPlayerTurn to set values for the currentPlayer than pass those same variables + currentPlayerMove to playergameplay

![image](https://github.com/user-attachments/assets/fa6baa5f-1279-47f3-9403-247841029516)
