### ISSUE TITLE
Both methods seem to be logical ones

### ISSUE THREAD

**Issue by AlexKap23** [Sosa09/TicTacToe#2]
https://github.com/Sosa09/TicTacToe/blob/5ece4deb3de4ac4d64fa7dc82f368814964aebcc/TicTacToe/Program.cs#L149-L173

They are used inside your program and they don't have any interaction with the user. They seem to be logical ones. You can move them to the GameLogic class

**Comment by Sosa09** [comment]
Makes sense, I had similar kind of function performing same action like putting value in grid or assigning value.

DONE
