### ISSUE TITLE
This can be a UIExperienceMethod

### ISSUE THREAD

**Issue by AlexKap23** [Sosa09/TicTacToe#3]
https://github.com/Sosa09/TicTacToe/blob/5ece4deb3de4ac4d64fa7dc82f368814964aebcc/TicTacToe/Program.cs#L69-L79

This method can be saved into the UIExperience class

**Comment by Sosa09** [comment]
Removed function from Program and refactored DisplayWinner from UIExperience class which now is called DisplayFinalResult which takes 3 args result code, grid, winnerName with default value "" in case of draft

Mainn function in program handles the result 
![image](https://github.com/user-attachments/assets/96df6e4d-8d72-4f50-942d-27ee59aeabb9)

**Comment by Sosa09** [comment]
done
