### ISSUE TITLE
Not a good name for a method

### ISSUE THREAD

**Issue by AlexKap23** [Sosa09/TicTacToe#5]
https://github.com/Sosa09/TicTacToe/blob/701d6f1231e8ede2de63f518c140059e2826ab09/TicTacToe/Program.cs#L89

methods should have a name that contains a combination of verb-noun. The verb is there to determine the action and the noun is there for who does the action or what the action is about. 

PlayerGamePlay seems like a name for a variable and not a method. Can you think of a better name that is using the above practice?

**Comment by Sosa09** [comment]
Modified The function playerGamePlay
1. renamed the function to GetValidPlayerPosition
2. removed the line where i update the grid, this is now done in the main GameLogic.SetCharPositon(...)
3. return type to int[]
